### ISSUE TITLE
no output files created

### ISSUE THREAD

**Issue by isisarantes** [isaacovercast/easySFS#27]
Hello,

I'm trying to create the files, when I use preview I can see it. 
```
(easySFS) isisarantes@MacBook-Pro easySFS % ./easySFS.py -i /Users/isisarantes/OneDrive/Doutorado/RADseq_analysis/delimitR/Dendro_m35_all.vcf -p /Users/isisarantes/OneDrive/Doutorado/RADseq_analysis/delimitR/pops_file.txt -a --preview         
Processing 8 populations - odict_keys(['pop4', 'pop5', 'pop6', 'pop3', 'pop7', 'pop8', 'pop1', 'pop2'])

    Running preview mode. We will print out the results for # of segregating sites
    for multiple values of projecting down for each population. The dadi
    manual recommends maximizing the # of seg sites for projections, but also
    a balance must be struck between # of seg sites and sample size.

    For each population you should choose the value of the projection that looks
    best and then rerun easySFS with the `--proj` flag.
    
pop4
(2, 69.0)	(3, 103.0)	(4, 127.0)	(5, 145.0)	(6, 161.0)	(7, 173.0)	(8, 185.0)	


pop5
(2, 84.0)	(3, 121.0)	(4, 147.0)	


pop6
(2, 53.0)	(3, 78.0)	(4, 94.0)	


pop3
(2, 60.0)	(3, 90.0)	(4, 109.0)	(5, 119.0)	(6, 128.0)	


pop7
(2, 82.0)	(3, 122.0)	(4, 153.0)	(5, 180.0)	(6, 204.0)	(7, 226.0)	(8, 245.0)	(9, 263.0)	(10, 280.0)	(11, 296.0)	(12, 312.0)	(13, 326.0)	(14, 340.0(15, 346.0)	(16, 358.0)	


pop8
(2, 67.0)	(3, 100.0)	(4, 126.0)	(5, 148.0)	(6, 167.0)	(7, 185.0)	(8, 201.0)	(9, 216.0)	(10, 231.0)	(11, 243.0)	(12, 256.0)	(13, 267.0)	(14, 279.0(15, 286.0)	(16, 297.0)	


pop1
(2, 144.0)	(3, 216.0)	(4, 258.0)	(5, 278.0)	(6, 292.0)	


pop2
(2, 65.0)	(3, 96.0)	(4, 118.0)	(5, 135.0)	(6, 150.0)	(7, 162.0)	(8, 173.0)	(9, 177.0)	(10, 185.0)
```

Then,
```
(easySFS) isisarantes@MacBook-Pro easySFS % ./easySFS.py -i /Users/isisarantes/OneDrive/Doutorado/RADseq_analysis/delimitR/Dendro_m35_all.vcf -p /Users/isisarantes/OneDrive/Doutorado/RADseq_analysis/delimitR/pops_file.txt --proj 12,40 -f
Processing 8 populations - odict_keys(['pop4', 'pop5', 'pop6', 'pop3', 'pop7', 'pop8', 'pop1', 'pop2'])
  Sampling one snp per locus
You must pass in the same number of values for projection as you have populations specified

N pops = 8
N projections = 2
Projections = [12, 40]

(easySFS) isisarantes@MacBook-Pro easySFS % ls
README.md		example_files		output
easySFS.py		jupyter-notebooks
(easySFS) isisarantes@MacBook-Pro easySFS % ls output 
dadi		datadict.txt	fastsimcoal2
(easySFS) isisarantes@MacBook-Pro easySFS % ls output/fastsimcoal2 
```
The folders are empty... I don't get any error messages. Idk if it's because I didn't use the right number of projections. I'm not sure how to determine this <--proj 12,40>.

Thanks in advance!
Ísis

**Comment by isaacovercast** [comment]
Hi Isis, You're getting an error message, I just don't write SCARY error messages in my code ;p The error is here:

`You must pass in the same number of values for projection as you have populations specified`

You have 8 populations so you have to pass in 8 numbers of samples to project each population down to. This is the reason for the --preview mode, to show you how many segregating sites there are for each projection value so you can maximize this quantity.

Hope that helps! Please close this issue when you have a chance to run it and get output files.

**Comment by isisarantes** [comment]
lol 
I'm foreign and I had to ask my American husband what I was missing. lolol
Now got this error:

```
python(16344,0x10d741dc0) malloc: can't allocate region
:*** mach_vm_map(size=189267620445667328, flags: 60000100) failed (error code=3)
python(16344,0x10d741dc0) malloc: *** set a breakpoint in malloc_error_break to debug
Traceback (most recent call last):
  File "./easySFS.py", line 650, in <module>
    main()
  File "./easySFS.py", line 635, in main
    sfs_file = dadi_multiSFS(dd, pops, proj=proj, unfold=args.unfolded, outdir=outdir, prefix=prefix, dtype=args.dtype)
  File "./easySFS.py", line 156, in dadi_multiSFS
    fs = dadi.Spectrum.from_data_dict(dd, pops, proj, polarized=unfold)
  File "/Users/isisarantes/opt/anaconda2/envs/easySFS/lib/python3.7/site-packages/dadi/Spectrum_mod.py", line 1848, in from_data_dict
    fs = Spectrum._from_count_dict(cd, projections, polarized, pop_ids)
  File "/Users/isisarantes/opt/anaconda2/envs/easySFS/lib/python3.7/site-packages/dadi/Spectrum_mod.py", line 1874, in _from_count_dict
    fs_total = dadi.Spectrum(numpy.zeros(numpy.array(projections)+1),
MemoryError: Unable to allocate 168. PiB for an array with shape (51, 71, 91, 101, 151, 161, 171, 171) and data type float64
```
My python version is 3.7.6
```
(easySFS) isisarantes@MacBook-Pro easySFS % python
Python 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 22:45:16) 
[Clang 9.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```

It's not creating the MultiSFS outputs.
Thank you in advance!

**Comment by isaacovercast** [comment]
+1 Glad it worked.
