### ISSUE TITLE
NameError: name 'raw_input' is not defined

### ISSUE THREAD

**Issue by janxkoci** [isaacovercast/easySFS#33]
I'm trying to run easySFS on my dataset and I got this error.

I have a VCF file (produced by `freebayes` and processed with few other tools, like `vcflib` and `bcftools`) with 81 samples, but I want to run the first analysis on only a subset of them, as I indicated in my `POPULATIONS` file.

Here is my command and the full error with traceback:

```bash
$ easySFS.py -i ../ingroup_cenpt2_pass_snps_annot_vcffilter_noMTDNA_biallelic_lessNA.vcf -p pop_file_sex.tsv -a --preview
Processing 5 populations - odict_keys(['TT', 'EE', 'PP', 'NN', 'CC'])

Samples in pops file not present in VCF: 
Samples in VCF not present in pops file: csc011, csc067, csc014, csc057, csc018, csc054, csc012, csc015, csc096, csc065, csc095, csc047, csc078, csc088, csc082, csc051, csc063, csc048, csc087, csc055, csc076, csc052, csc079, csc016, csc061, csc086, csc069, csc050, csc062, csc093, csc056, csc044, csc017, csc071, csc013, csc046, csc089, csc073, csc066, csc074, csc094, csc059, csc085, csc098, csc053, csc166, csc090, csc058
Traceback (most recent call last):
  File "/home/users/koci/bin/easySFS.py", line 653, in <module>
    main()
  File "/home/users/koci/bin/easySFS.py", line 602, in main
    ind2pop, indnames, pops = check_inputs(ind2pop, indnames, pops)
  File "/home/users/koci/bin/easySFS.py", line 447, in check_inputs
    cont = raw_input("\nContinue, excluding samples not in both pops file and VCF? (yes/no)\n")
NameError: name 'raw_input' is not defined
```

I'm not very good in python, so any pointers to what might be wrong will be appreciated.

**Comment by isaacovercast** [comment]
Thanks for reporting. This is fixed. 844e833
